### ISSUE TITLE
LiftBedToSam require some package support 

### ISSUE THREAD

**Issue by yangyxt** [CMU-SAFARI/AirLift#7]
I've found this issue when using LiftBedToSam

/paedyl01/disk1/yangyxt/ngs_scripts/AirLift_old/5-merge/liftBedToSam: /software/gcc/4.9.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /paedyl01/disk1/yangyxt/ngs_scripts/AirLift_old/5-merge/liftBedToSam)

Could you pls help indicate which package should I install to avoid this issue ? 
Thanks!

**Comment by yangyxt** [comment]
Dear Officer,

I tried to contact our IT technician to help solve this but failed. 

Here is his response as a screenshot:
![image](https://user-images.githubusercontent.com/40780228/102311138-4551a900-3fa7-11eb-959a-470c1ea911b1.png)


Could you pls help solve this?

**Comment by canfirtina** [comment]
Hi @yangyxt 

liftBedToSam is now deprecated in the current version of AirLift.
